/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 20
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_cond = 2,
  anon_sym_if = 3,
  anon_sym_let = 4,
  anon_sym_load = 5,
  anon_sym_match = 6,
  anon_sym_prog = 7,
  anon_sym_quote = 8,
  anon_sym_syscall = 9,
  anon_sym_unless = 10,
  anon_sym_RPAREN = 11,
  anon_sym_def = 12,
  anon_sym_BSLASH = 13,
  sym_number = 14,
  sym_char = 15,
  sym_string = 16,
  anon_sym_nil = 17,
  anon_sym_t = 18,
  aux_sym_symbol_token1 = 19,
  anon_sym_TILDE = 20,
  anon_sym_BQUOTE = 21,
  anon_sym_SQUOTE = 22,
  anon_sym_COMMA = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym__sexp = 26,
  sym_special_form = 27,
  sym_function_definition = 28,
  sym_lambda = 29,
  sym__atom = 30,
  sym_symbol = 31,
  sym_tilde = 32,
  sym_backquote = 33,
  sym_quote = 34,
  sym_unquote = 35,
  sym_list = 36,
  aux_sym_source_file_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_cond] = "cond",
  [anon_sym_if] = "if",
  [anon_sym_let] = "let",
  [anon_sym_load] = "load",
  [anon_sym_match] = "match",
  [anon_sym_prog] = "prog",
  [anon_sym_quote] = "quote",
  [anon_sym_syscall] = "syscall",
  [anon_sym_unless] = "unless",
  [anon_sym_RPAREN] = ")",
  [anon_sym_def] = "def",
  [anon_sym_BSLASH] = "\\",
  [sym_number] = "number",
  [sym_char] = "char",
  [sym_string] = "string",
  [anon_sym_nil] = "nil",
  [anon_sym_t] = "t",
  [aux_sym_symbol_token1] = "symbol_token1",
  [anon_sym_TILDE] = "~",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_COMMA] = ",",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__sexp] = "_sexp",
  [sym_special_form] = "special_form",
  [sym_function_definition] = "function_definition",
  [sym_lambda] = "lambda",
  [sym__atom] = "_atom",
  [sym_symbol] = "symbol",
  [sym_tilde] = "tilde",
  [sym_backquote] = "backquote",
  [sym_quote] = "quote",
  [sym_unquote] = "unquote",
  [sym_list] = "list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_cond] = anon_sym_cond,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_load] = anon_sym_load,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_prog] = anon_sym_prog,
  [anon_sym_quote] = anon_sym_quote,
  [anon_sym_syscall] = anon_sym_syscall,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [sym_number] = sym_number,
  [sym_char] = sym_char,
  [sym_string] = sym_string,
  [anon_sym_nil] = anon_sym_nil,
  [anon_sym_t] = anon_sym_t,
  [aux_sym_symbol_token1] = aux_sym_symbol_token1,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__sexp] = sym__sexp,
  [sym_special_form] = sym_special_form,
  [sym_function_definition] = sym_function_definition,
  [sym_lambda] = sym_lambda,
  [sym__atom] = sym__atom,
  [sym_symbol] = sym_symbol,
  [sym_tilde] = sym_tilde,
  [sym_backquote] = sym_backquote,
  [sym_quote] = sym_quote,
  [sym_unquote] = sym_unquote,
  [sym_list] = sym_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cond] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_load] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prog] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_quote] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_syscall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_nil] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_symbol_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sexp] = {
    .visible = false,
    .named = true,
  },
  [sym_special_form] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_tilde] = {
    .visible = true,
    .named = true,
  },
  [sym_backquote] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_docstring = 1,
  field_name = 2,
  field_parameters = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_docstring] = "docstring",
  [field_name] = "name",
  [field_parameters] = "parameters",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_parameters, 2},
  [1] =
    {field_name, 2},
    {field_parameters, 3},
  [3] =
    {field_docstring, 4},
    {field_name, 2},
    {field_parameters, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static const TSCharacterRange aux_sym_symbol_token1_character_set_1[] = {
  {'!', '!'}, {'#', '&'}, {'*', '+'}, {'-', '-'}, {'/', '/'}, {':', ':'}, {'<', ']'}, {'_', '_'},
  {'a', '}'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 1,
        '\'', 91,
        '(', 8,
        ')', 18,
        ',', 92,
        '-', 74,
        ';', 93,
        '\\', 20,
        '^', 3,
        '`', 90,
        'c', 63,
        'd', 49,
        'i', 51,
        'l', 47,
        'm', 40,
        'n', 55,
        'p', 65,
        'q', 72,
        's', 73,
        't', 38,
        'u', 61,
        '~', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('!' <= lookahead && lookahead <= '+') ||
          ('/' <= lookahead && lookahead <= '}')) ADVANCE(88);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ';') ADVANCE(93);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == 't') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (set_contains(aux_sym_symbol_token1_character_set_1, 9, lookahead)) ADVANCE(88);
      END_STATE();
    case 3:
      if (lookahead == '\\') ADVANCE(4);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == '\\' ||
          lookahead == 'e' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == '"' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'e' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(1);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 1,
        '\'', 91,
        '(', 8,
        ')', 18,
        ',', 92,
        '-', 74,
        ';', 93,
        '^', 3,
        '`', 90,
        'n', 55,
        't', 38,
        '~', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('!' <= lookahead && lookahead <= '+') ||
          ('/' <= lookahead && lookahead <= '}')) ADVANCE(88);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_cond);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_let);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_load);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_match);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(83);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_prog);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_quote);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(83);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_syscall);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(81);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_unless);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(82);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(39);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(76);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(75);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(77);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(78);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(79);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(80);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(81);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(82);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(83);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_nil);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'a') ADVANCE(70);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'c') ADVANCE(54);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'c') ADVANCE(42);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'd') ADVANCE(9);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'e') ADVANCE(69);
      if (lookahead == 'o') ADVANCE(41);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'e') ADVANCE(68);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'g') ADVANCE(14);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'h') ADVANCE(13);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'i') ADVANCE(56);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'l') ADVANCE(37);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(82);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'l') ADVANCE(50);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'l') ADVANCE(57);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(83);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'n') ADVANCE(45);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'n') ADVANCE(58);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'o') ADVANCE(53);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'o') ADVANCE(60);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'o') ADVANCE(71);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'r') ADVANCE(62);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 's') ADVANCE(17);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(83);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 's') ADVANCE(44);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 't') ADVANCE(11);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 't') ADVANCE(43);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 't') ADVANCE(48);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'u') ADVANCE(64);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == 'y') ADVANCE(67);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(39);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(83);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(84);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(86);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '-') ||
          ('/' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '}')) ADVANCE(87);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_cond] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_load] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_prog] = ACTIONS(1),
    [anon_sym_quote] = ACTIONS(1),
    [anon_sym_syscall] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_nil] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [aux_sym_symbol_token1] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(36),
    [sym__sexp] = STATE(5),
    [sym_special_form] = STATE(5),
    [sym_function_definition] = STATE(5),
    [sym_lambda] = STATE(5),
    [sym__atom] = STATE(5),
    [sym_symbol] = STATE(5),
    [sym_tilde] = STATE(5),
    [sym_backquote] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_unquote] = STATE(5),
    [sym_list] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [sym_char] = ACTIONS(11),
    [sym_string] = ACTIONS(11),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__sexp] = STATE(6),
    [sym_special_form] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_lambda] = STATE(6),
    [sym__atom] = STATE(6),
    [sym_symbol] = STATE(6),
    [sym_tilde] = STATE(6),
    [sym_backquote] = STATE(6),
    [sym_quote] = STATE(6),
    [sym_unquote] = STATE(6),
    [sym_list] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_cond] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(23),
    [anon_sym_load] = ACTIONS(23),
    [anon_sym_match] = ACTIONS(23),
    [anon_sym_prog] = ACTIONS(23),
    [anon_sym_quote] = ACTIONS(23),
    [anon_sym_syscall] = ACTIONS(23),
    [anon_sym_unless] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_def] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(29),
    [sym_number] = ACTIONS(31),
    [sym_char] = ACTIONS(33),
    [sym_string] = ACTIONS(33),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__sexp] = STATE(3),
    [sym_special_form] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_symbol] = STATE(3),
    [sym_tilde] = STATE(3),
    [sym_backquote] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(37),
    [anon_sym_RPAREN] = ACTIONS(35),
    [sym_number] = ACTIONS(40),
    [sym_char] = ACTIONS(43),
    [sym_string] = ACTIONS(43),
    [anon_sym_nil] = ACTIONS(46),
    [anon_sym_t] = ACTIONS(46),
    [aux_sym_symbol_token1] = ACTIONS(46),
    [anon_sym_TILDE] = ACTIONS(49),
    [anon_sym_BQUOTE] = ACTIONS(52),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [anon_sym_COMMA] = ACTIONS(58),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__sexp] = STATE(3),
    [sym_special_form] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_symbol] = STATE(3),
    [sym_tilde] = STATE(3),
    [sym_backquote] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_number] = ACTIONS(63),
    [sym_char] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__sexp] = STATE(3),
    [sym_special_form] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_symbol] = STATE(3),
    [sym_tilde] = STATE(3),
    [sym_backquote] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(63),
    [sym_char] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__sexp] = STATE(3),
    [sym_special_form] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_symbol] = STATE(3),
    [sym_tilde] = STATE(3),
    [sym_backquote] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(69),
    [sym_number] = ACTIONS(63),
    [sym_char] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__sexp] = STATE(8),
    [sym_special_form] = STATE(8),
    [sym_function_definition] = STATE(8),
    [sym_lambda] = STATE(8),
    [sym__atom] = STATE(8),
    [sym_symbol] = STATE(8),
    [sym_tilde] = STATE(8),
    [sym_backquote] = STATE(8),
    [sym_quote] = STATE(8),
    [sym_unquote] = STATE(8),
    [sym_list] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(71),
    [sym_number] = ACTIONS(73),
    [sym_char] = ACTIONS(75),
    [sym_string] = ACTIONS(75),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__sexp] = STATE(3),
    [sym_special_form] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_symbol] = STATE(3),
    [sym_tilde] = STATE(3),
    [sym_backquote] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(77),
    [sym_number] = ACTIONS(63),
    [sym_char] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym__sexp] = STATE(3),
    [sym_special_form] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_symbol] = STATE(3),
    [sym_tilde] = STATE(3),
    [sym_backquote] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(79),
    [sym_number] = ACTIONS(63),
    [sym_char] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym__sexp] = STATE(4),
    [sym_special_form] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_lambda] = STATE(4),
    [sym__atom] = STATE(4),
    [sym_symbol] = STATE(4),
    [sym_tilde] = STATE(4),
    [sym_backquote] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_unquote] = STATE(4),
    [sym_list] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(81),
    [sym_number] = ACTIONS(83),
    [sym_char] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [sym__sexp] = STATE(13),
    [sym_special_form] = STATE(13),
    [sym_function_definition] = STATE(13),
    [sym_lambda] = STATE(13),
    [sym__atom] = STATE(13),
    [sym_symbol] = STATE(13),
    [sym_tilde] = STATE(13),
    [sym_backquote] = STATE(13),
    [sym_quote] = STATE(13),
    [sym_unquote] = STATE(13),
    [sym_list] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(87),
    [sym_number] = ACTIONS(89),
    [sym_char] = ACTIONS(91),
    [sym_string] = ACTIONS(91),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [sym__sexp] = STATE(9),
    [sym_special_form] = STATE(9),
    [sym_function_definition] = STATE(9),
    [sym_lambda] = STATE(9),
    [sym__atom] = STATE(9),
    [sym_symbol] = STATE(9),
    [sym_tilde] = STATE(9),
    [sym_backquote] = STATE(9),
    [sym_quote] = STATE(9),
    [sym_unquote] = STATE(9),
    [sym_list] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(93),
    [sym_number] = ACTIONS(95),
    [sym_char] = ACTIONS(97),
    [sym_string] = ACTIONS(99),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [sym__sexp] = STATE(3),
    [sym_special_form] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_lambda] = STATE(3),
    [sym__atom] = STATE(3),
    [sym_symbol] = STATE(3),
    [sym_tilde] = STATE(3),
    [sym_backquote] = STATE(3),
    [sym_quote] = STATE(3),
    [sym_unquote] = STATE(3),
    [sym_list] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(101),
    [sym_number] = ACTIONS(63),
    [sym_char] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [sym__sexp] = STATE(10),
    [sym_special_form] = STATE(10),
    [sym_function_definition] = STATE(10),
    [sym_lambda] = STATE(10),
    [sym__atom] = STATE(10),
    [sym_symbol] = STATE(10),
    [sym_tilde] = STATE(10),
    [sym_backquote] = STATE(10),
    [sym_quote] = STATE(10),
    [sym_unquote] = STATE(10),
    [sym_list] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(103),
    [sym_char] = ACTIONS(105),
    [sym_string] = ACTIONS(105),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [sym__sexp] = STATE(20),
    [sym_special_form] = STATE(20),
    [sym_function_definition] = STATE(20),
    [sym_lambda] = STATE(20),
    [sym__atom] = STATE(20),
    [sym_symbol] = STATE(20),
    [sym_tilde] = STATE(20),
    [sym_backquote] = STATE(20),
    [sym_quote] = STATE(20),
    [sym_unquote] = STATE(20),
    [sym_list] = STATE(20),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(107),
    [sym_char] = ACTIONS(109),
    [sym_string] = ACTIONS(109),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [sym__sexp] = STATE(23),
    [sym_special_form] = STATE(23),
    [sym_function_definition] = STATE(23),
    [sym_lambda] = STATE(23),
    [sym__atom] = STATE(23),
    [sym_symbol] = STATE(23),
    [sym_tilde] = STATE(23),
    [sym_backquote] = STATE(23),
    [sym_quote] = STATE(23),
    [sym_unquote] = STATE(23),
    [sym_list] = STATE(23),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(111),
    [sym_char] = ACTIONS(113),
    [sym_string] = ACTIONS(113),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [sym__sexp] = STATE(24),
    [sym_special_form] = STATE(24),
    [sym_function_definition] = STATE(24),
    [sym_lambda] = STATE(24),
    [sym__atom] = STATE(24),
    [sym_symbol] = STATE(24),
    [sym_tilde] = STATE(24),
    [sym_backquote] = STATE(24),
    [sym_quote] = STATE(24),
    [sym_unquote] = STATE(24),
    [sym_list] = STATE(24),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(115),
    [sym_char] = ACTIONS(117),
    [sym_string] = ACTIONS(117),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(18)] = {
    [sym__sexp] = STATE(22),
    [sym_special_form] = STATE(22),
    [sym_function_definition] = STATE(22),
    [sym_lambda] = STATE(22),
    [sym__atom] = STATE(22),
    [sym_symbol] = STATE(22),
    [sym_tilde] = STATE(22),
    [sym_backquote] = STATE(22),
    [sym_quote] = STATE(22),
    [sym_unquote] = STATE(22),
    [sym_list] = STATE(22),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(119),
    [sym_char] = ACTIONS(121),
    [sym_string] = ACTIONS(121),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(19)] = {
    [sym__sexp] = STATE(12),
    [sym_special_form] = STATE(12),
    [sym_function_definition] = STATE(12),
    [sym_lambda] = STATE(12),
    [sym__atom] = STATE(12),
    [sym_symbol] = STATE(12),
    [sym_tilde] = STATE(12),
    [sym_backquote] = STATE(12),
    [sym_quote] = STATE(12),
    [sym_unquote] = STATE(12),
    [sym_list] = STATE(12),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_number] = ACTIONS(123),
    [sym_char] = ACTIONS(125),
    [sym_string] = ACTIONS(125),
    [anon_sym_nil] = ACTIONS(13),
    [anon_sym_t] = ACTIONS(13),
    [aux_sym_symbol_token1] = ACTIONS(13),
    [anon_sym_TILDE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(127), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [21] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(131), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [42] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(135), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [63] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(147), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(151), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [147] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(155), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [168] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(159), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [189] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(163), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(167), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [231] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(171), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [252] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(175), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [273] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(179), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [294] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 4,
      sym_number,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
    ACTIONS(183), 9,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_char,
      sym_string,
      anon_sym_TILDE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_COMMA,
  [315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(19), 1,
      sym_symbol,
    ACTIONS(13), 3,
      anon_sym_nil,
      anon_sym_t,
      aux_sym_symbol_token1,
  [327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(20)] = 0,
  [SMALL_STATE(21)] = 21,
  [SMALL_STATE(22)] = 42,
  [SMALL_STATE(23)] = 63,
  [SMALL_STATE(24)] = 84,
  [SMALL_STATE(25)] = 105,
  [SMALL_STATE(26)] = 126,
  [SMALL_STATE(27)] = 147,
  [SMALL_STATE(28)] = 168,
  [SMALL_STATE(29)] = 189,
  [SMALL_STATE(30)] = 210,
  [SMALL_STATE(31)] = 231,
  [SMALL_STATE(32)] = 252,
  [SMALL_STATE(33)] = 273,
  [SMALL_STATE(34)] = 294,
  [SMALL_STATE(35)] = 315,
  [SMALL_STATE(36)] = 327,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backquote, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backquote, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tilde, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tilde, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_form, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_form, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, 0, 1),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 4, 0, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_form, 4, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_form, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 2),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, 0, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 5, 0, 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 5, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, 0, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 2),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, 0, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 3),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7, 0, 3),
  [187] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_slisp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "slisp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
